const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),{webcrypto}=require('node:crypto'),{indexedDB}=require('fake-indexeddb');
const context=vm.createContext({indexedDB,crypto:webcrypto,navigator:{locks:{request:async(n,fn)=>fn()}},TextEncoder,TextDecoder,Uint8Array,atob,btoa,console});
for(const file of ['routine.js','storage.js','vault.js'])vm.runInContext(fs.readFileSync(require('node:path').join(__dirname,'../static',file),'utf8'),context);
const storage=vm.runInContext('DailyStorage',context),rules=vm.runInContext('DailyRoutine',context);
(async()=>{
 const today=(()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;})(),weekday=new Date(today+'T12:00:00').getDay();
 const habits=[{id:'read',label:'Read',goal:'A page',days:[weekday]},{id:'walk',label:'Walk',goal:'Ten minutes',days:[weekday],paused:true},{id:'learn',label:'Learn',goal:'A lesson',days:[(weekday+1)%7]}];
 assert.equal(rules.plan(habits,today).length,1);assert.throws(()=>rules.validate([{...habits[0],days:[]}])) ;assert.throws(()=>rules.validate([habits[0],habits[0]]));assert.throws(()=>rules.validate([{...habits[0],id:'constructor'}]));assert.throws(()=>rules.validate(Array.from({length:13},(_,i)=>({...habits[0],id:'h'+i}))));
 await storage.request('/auth/register','POST',{username:'Routines QA'});await storage.request('/preferences','PUT',{habits});let day=await storage.request('/habits/today');day.routine=habits;day.habits.read=true;day.habits.walk=true;day.details.read={note:'PRIVATE_CUSTOM_NOTE'};const result=await storage.request('/habits/today','POST',day);assert.equal(result.score,100);
 const saved=await storage.request('/habits/today');await storage.request('/preferences','PUT',{habits:[{...habits[0],label:'New label',paused:true}]});const exported=await storage.request('/export');assert.equal(exported.days[0].routine[0].label,'Read');assert.equal(exported.days[0].score,100);assert.equal((await storage.request('/stats')).avg,100);
 const legacy={date:'2020-01-02',habits:{exercise:true},crosses:{},details:{},score:20};await storage.restore({days:[legacy]});assert.equal((await storage.request('/export')).days.find(d=>d.date===legacy.date).score,20);
 const setup=await storage.request('/auth/create','POST',{username:'Routines QA',password:'routine-password-123',migrate:true});await storage.request('/auth/finish');const envelope=await storage.request('/cloud/snapshot');assert.ok(!JSON.stringify(envelope).includes('PRIVATE_CUSTOM_NOTE'));assert.ok(!JSON.stringify(envelope).includes('routine-password-123'));assert.equal(envelope.id,setup.id);
 await storage.request('/auth/logout');await storage.request('/cloud/import','POST',{envelope});await storage.request('/auth/login','POST',{id:setup.id,password:'routine-password-123'});assert.equal((await storage.request('/export')).days.find(d=>d.date===today).details.read.note,'PRIVATE_CUSTOM_NOTE');await assert.rejects(()=>storage.request('/cloud/import','POST',{envelope:{id:'bad'}}));
 const off={date:today,routine:[{...habits[0],paused:true}],habits:{read:true},crosses:{},details:{}};assert.equal(rules.score(off),0);assert.equal(rules.metrics([{...off,score:0}]).days,0);
 console.log('PASS: custom habits, scheduling/pauses, validation, historical snapshots/scores, no-plan days and encrypted cloud envelope round trip.');
})().catch(e=>{console.error(e);process.exitCode=1;});
