const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),{webcrypto}=require('node:crypto');
const {indexedDB}=require('fake-indexeddb');
const queues=new Map(),locks={request(name,fn){const prior=queues.get(name)||Promise.resolve();const result=prior.catch(()=>{}).then(fn);queues.set(name,result);return result;}};
function tab(){const c=vm.createContext({indexedDB,crypto:webcrypto,navigator:{locks},TextEncoder,TextDecoder,Uint8Array,atob,btoa,console});for(const file of ['routine.js','storage.js','vault.js'])vm.runInContext(fs.readFileSync(require('node:path').join(__dirname,'../static',file),'utf8'),c);return vm.runInContext('DailyStorage',c);}
function inspect(){return new Promise((resolve,reject)=>{const r=indexedDB.open('daily-personal-workspace',1);r.onerror=()=>reject(r.error);r.onsuccess=()=>{const t=r.result.transaction('records'),s=t.objectStore('records'),out={};const q=s.openCursor();q.onsuccess=()=>{const c=q.result;if(c){out[c.key]=c.value;c.continue();}else resolve(out);};};});}
(async()=>{
 const a=tab();await a.request('/auth/register','POST',{username:'Legacy QA'});
 let day=await a.request('/habits/today');day.habits.exercise=true;day.details.exercise={note:'SECRET_JOURNAL_NOTE'};await a.request('/habits/today','POST',day);
 const setup=await a.request('/auth/create','POST',{username:'Legacy QA',password:'qa-password-123',migrate:true});assert.ok(setup.id.startsWith('daily-'));await a.request('/auth/finish');
 const stored=await inspect();assert.equal(stored.profile,undefined);assert.equal(stored['day:'+day.date],undefined);assert.ok(!JSON.stringify(stored).includes('SECRET_JOURNAL_NOTE'));assert.ok(!JSON.stringify(stored).includes('qa-password-123'));
 assert.equal((await a.request('/export')).days[0].details.exercise.note,'SECRET_JOURNAL_NOTE');assert.equal((await a.request('/stats')).avg,20);
 const b=tab();await assert.rejects(()=>b.request('/auth/me'),e=>e.status===401);await assert.rejects(()=>b.request('/auth/login','POST',{id:setup.id,password:'wrong-password'}),e=>e.status===401);
 await b.request('/auth/login','POST',{id:setup.id,password:'qa-password-123'});const stale=await b.request('/habits/today'),fresh=await a.request('/habits/today');fresh.habits.diet=true;await a.request('/habits/today','POST',fresh);await assert.rejects(()=>b.request('/habits/today','POST',stale),e=>e.status===409);
 await a.request('/auth/logout');await assert.rejects(()=>a.request('/export'),e=>e.status===401);
 const other=await a.request('/auth/create','POST',{username:'Other QA',password:'other-password-123'});await a.request('/auth/finish');assert.equal((await a.request('/export')).days.length,0);assert.equal((await b.request('/export')).days.length,1);assert.equal((await b.request('/export')).profile.id,setup.id);
 await a.restore({days:[],profile:{username:'Renamed'}});assert.equal((await a.request('/auth/me')).id,other.id);
 const large=Array.from({length:100},(_,i)=>{const date=new Date(Date.now()-(i+200)*86400000).toISOString().slice(0,10);return {date,habits:{exercise:true},crosses:{},details:{exercise:{note:'Private long note '.repeat(80)}}};});await a.restore({days:large});assert.equal((await a.request('/export')).days.length,100);assert.ok(!JSON.stringify(await inspect()).includes('Private long note'));
 await b.request('/auth/logout');await assert.rejects(()=>b.request('/auth/recover','POST',{id:setup.id,recovery:'0'.repeat(64),password:'new-password-123'}),e=>e.status===401);
 await b.request('/auth/recover','POST',{id:setup.id,recovery:setup.recovery,password:'new-password-123'});assert.equal((await b.request('/export')).days[0].score,40);await b.request('/auth/logout');await assert.rejects(()=>b.request('/auth/login','POST',{id:setup.id,password:'qa-password-123'}),e=>e.status===401);await b.request('/auth/login','POST',{id:setup.id,password:'new-password-123'});
 // Cancellation never commits a workspace; migration rejects concurrent edits.
 const c=tab();await c.request('/auth/register','POST',{username:'Concurrent legacy'});let d=await c.request('/habits/today');await c.request('/habits/today','POST',d);await c.request('/auth/create','POST',{username:'Concurrent legacy',password:'cancel-password-123',migrate:true});d=await c.request('/habits/today');d.habits.project=true;await c.request('/habits/today','POST',d);await assert.rejects(()=>c.request('/auth/finish'),/Another tab changed/);assert.equal((await c.request('/habits/today')).score,20);await c.request('/auth/cancel');
 console.log('PASS: encrypted migration, preserved notes, wrong credentials, reload lock, logout, two-account isolation, restore identity, recovery/password reset, stale-tab conflict and cancelled/concurrent migration.');
})().catch(e=>{console.error(e);process.exitCode=1;});
